# Generated by Django 3.2 on 2021-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
