# Generated by Django 3.2 on 2021-04-20 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places_remember_app', '0002_alter_memory_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, upload_to='memory_photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
