# Generated by Django 3.2 on 2021-04-22 14:17

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0003_auto_20210420_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=django_google_maps.fields.AddressField(max_length=100, verbose_name='Location'),
        ),
    ]
