# Generated by Django 3.2 on 2021-04-23 10:17

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0005_alter_memory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='Location'),
        ),
    ]
