# Generated by Django 3.2 on 2021-04-23 10:22

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0006_alter_memory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Location'),
        ),
    ]
