# Generated by Django 3.2 on 2021-04-23 11:50

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0011_memory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
        ),
    ]
