# Generated by Django 3.2 on 2021-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0016_alter_memory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
    ]
