# Generated by Django 3.2 on 2021-05-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0017_alter_memory_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='memory_photos/', verbose_name='Image'),
        ),
    ]
